/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/shared/Container.vue')['default']
    CSSIcon: typeof import('./components/icons/CSSIcon.vue')['default']
    DividerY: typeof import('./components/shared/DividerY.vue')['default']
    FrontEndIcon: typeof import('./components/icons/FrontEndIcon.vue')['default']
    HTMLIcon: typeof import('./components/icons/HTMLIcon.vue')['default']
    IntersectionObserved: typeof import('./components/IntersectionObserved.vue')['default']
    Link: typeof import('./components/shared/Link.vue')['default']
    LinkRoute: typeof import('./components/shared/LinkRoute.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ReactIcon: typeof import('./components/icons/ReactIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypescriptIcon: typeof import('./components/icons/TypescriptIcon.vue')['default']
    VueIcon: typeof import('./components/icons/VueIcon.vue')['default']
  }
}
