// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/shared/Container.vue')['default']
    CSSIcon: typeof import('./components/icons/CSSIcon.vue')['default']
    DividerY: typeof import('./components/shared/DividerY.vue')['default']
    Experiment1: typeof import('./components/experiments/Experiment1.vue')['default']
    Experiment2: typeof import('./components/experiments/Experiment2.vue')['default']
    Experiment3: typeof import('./components/experiments/Experiment3.vue')['default']
    Experiment4: typeof import('./components/experiments/Experiment4.vue')['default']
    Experiment5: typeof import('./components/experiments/experiment5.vue')['default']
    FrontEndIcon: typeof import('./components/icons/FrontEndIcon.vue')['default']
    HTMLIcon: typeof import('./components/icons/HTMLIcon.vue')['default']
    IntersectionObserved: typeof import('./components/IntersectionObserved.vue')['default']
    Link: typeof import('./components/shared/Link.vue')['default']
    LinkRoute: typeof import('./components/shared/LinkRoute.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ReactIcon: typeof import('./components/icons/ReactIcon.vue')['default']
    Test: typeof import('./components/experiments/test.vue')['default']
    TypescriptIcon: typeof import('./components/icons/TypescriptIcon.vue')['default']
    VueIcon: typeof import('./components/icons/VueIcon.vue')['default']
  }
}

export { }
